case erlang:system_info(otp_release) of

    [$R|_] ->
        %% Rxx < 17.0, not border inclusive
        HashDefine = [{d,pre17}],
        case lists:keysearch(erl_opts, 1, CONFIG) of
            {value, {erl_opts, Opts}} ->
                lists:keyreplace(erl_opts,1,CONFIG,{erl_opts,Opts++HashDefine});
            false ->
                CONFIG ++ [{erl_opts, HashDefine}]
        end;

    _ ->
        %% "17", our future with map
        CONFIG

end.
